/*
 * ForgeGraal's native layer for quickjs-ng, in C.
 *
 * This is the same surface the Rust host (`runtime/`) provides, and deliberately so: both install
 * `globalThis.__forgegraal_native` with identical function names and shapes, so
 * `quickjs/runtime/native-modules.js` runs unchanged on either. The JavaScript above does not know
 * or care which backend is underneath.
 *
 * It exists because Rust cannot go low enough. Rust's standard library for 32-bit Windows imports
 * ProcessPrng (Windows 10), WaitOnAddress (Windows 8) and the api-ms-win-core-synch API set
 * (Windows 7), so the Rust host cannot serve Windows XP or Vista at all. This file uses only
 * Winsock 2 and CryptoAPI, both present since Windows 95/NT4, which is what makes XP reachable.
 *
 * TLS is mbedTLS, chosen for the same reason as everything else here: it is portable C with no
 * dependency on a modern platform, and its certificate verification uses a CA bundle compiled into
 * the binary rather than the operating system's store -- the store on a machine this old is a
 * decade stale and would reject Discord outright.
 *
 * Compression is miniz, a single public-domain file with the zlib API.
 */

#include "quickjs.h"
#ifdef __GLIBC__
#include <gnu/libc-version.h>
#endif

#include <stdlib.h>
#include <string.h>

#ifdef _WIN32
/* Winsock 2 and CryptoAPI only. Nothing here postdates Windows XP. */
#include <winsock2.h>
#include <ws2tcpip.h>
#include <windows.h>
#include <wincrypt.h>
typedef int socklen_t;
#define FG_CLOSE_SOCKET closesocket
#define FG_SOCKET_ERRNO WSAGetLastError()
#else
#include <arpa/inet.h>
#include <errno.h>
#include <netdb.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <sys/socket.h>
#include <unistd.h>
#define FG_CLOSE_SOCKET close
#define FG_SOCKET_ERRNO errno
typedef int SOCKET;
#define INVALID_SOCKET (-1)
#endif

#include "mbedtls/ctr_drbg.h"
#include "mbedtls/entropy.h"
#include "mbedtls/error.h"
#include "mbedtls/md.h"
#include "mbedtls/net_sockets.h"
#include "mbedtls/ssl.h"
#include "mbedtls/x509_crt.h"

#include "miniz.h"

/* The CA bundle compiled into the binary, generated by tools/gen-ca-bundle.sh. */
extern const char forgegraal_ca_bundle[];

/* ------------------------------------------------------------------ sockets */

#define FG_MAX_SOCKETS 256

typedef struct {
    int in_use;
    int is_tls;
    mbedtls_net_context net;
    mbedtls_ssl_context ssl;
    mbedtls_ssl_config conf;
    mbedtls_x509_crt cacert;
} fg_socket;

/* A fixed table rather than a growing map: ids are indices, an out-of-range or unused id is
   rejected, and JavaScript therefore cannot reach memory by guessing a number. */
static fg_socket fg_sockets[FG_MAX_SOCKETS];
static mbedtls_entropy_context fg_entropy;
static mbedtls_ctr_drbg_context fg_drbg;
static int fg_rng_ready = 0;

static int fg_rng_init(void)
{
    static const char *pers = "forgegraal";
    int ret;

    if (fg_rng_ready) {
        return 0;
    }
    mbedtls_entropy_init(&fg_entropy);
    mbedtls_ctr_drbg_init(&fg_drbg);
    ret = mbedtls_ctr_drbg_seed(&fg_drbg, mbedtls_entropy_func, &fg_entropy,
                                (const unsigned char *) pers, strlen(pers));
    if (ret != 0) {
        return ret;
    }
    fg_rng_ready = 1;
    return 0;
}

static JSValue fg_throw_mbedtls(JSContext *ctx, const char *what, int code)
{
    char buf[128];
    mbedtls_strerror(code, buf, sizeof(buf));
    return JS_ThrowInternalError(ctx, "%s failed: %s (-0x%04x)", what, buf, -code);
}

static fg_socket *fg_socket_get(JSContext *ctx, int32_t id)
{
    if (id < 0 || id >= FG_MAX_SOCKETS || !fg_sockets[id].in_use) {
        JS_ThrowInternalError(ctx, "socket %d does not exist (it was closed, or never opened)", id);
        return NULL;
    }
    return &fg_sockets[id];
}

static void fg_socket_release(fg_socket *sock)
{
    if (!sock->in_use) {
        return;
    }
    if (sock->is_tls) {
        mbedtls_ssl_close_notify(&sock->ssl);
        mbedtls_ssl_free(&sock->ssl);
        mbedtls_ssl_config_free(&sock->conf);
        mbedtls_x509_crt_free(&sock->cacert);
    }
    mbedtls_net_free(&sock->net);
    sock->in_use = 0;
    sock->is_tls = 0;
}

static JSValue fg_connect(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv)
{
    const char *host;
    char port_str[16];
    int32_t port = 0;
    int is_tls = 0;
    int id = -1;
    int ret;
    fg_socket *sock;

    if (argc < 2) {
        return JS_ThrowTypeError(ctx, "connect(host, port, tls) needs a host and a port");
    }
    host = JS_ToCString(ctx, argv[0]);
    if (!host) {
        return JS_EXCEPTION;
    }
    if (JS_ToInt32(ctx, &port, argv[1])) {
        JS_FreeCString(ctx, host);
        return JS_EXCEPTION;
    }
    if (argc > 2) {
        is_tls = JS_ToBool(ctx, argv[2]);
    }
    snprintf(port_str, sizeof(port_str), "%d", (int) port);

    for (int i = 0; i < FG_MAX_SOCKETS; i++) {
        if (!fg_sockets[i].in_use) {
            id = i;
            break;
        }
    }
    if (id < 0) {
        JS_FreeCString(ctx, host);
        return JS_ThrowInternalError(ctx, "too many open sockets (limit is %d)", FG_MAX_SOCKETS);
    }

    if (fg_rng_init() != 0) {
        JS_FreeCString(ctx, host);
        return JS_ThrowInternalError(ctx, "could not seed the random number generator");
    }

    sock = &fg_sockets[id];
    memset(sock, 0, sizeof(*sock));
    mbedtls_net_init(&sock->net);

    ret = mbedtls_net_connect(&sock->net, host, port_str, MBEDTLS_NET_PROTO_TCP);
    if (ret != 0) {
        mbedtls_net_free(&sock->net);
        JSValue err = fg_throw_mbedtls(ctx, "connect", ret);
        JS_FreeCString(ctx, host);
        return err;
    }

    if (is_tls) {
        mbedtls_ssl_init(&sock->ssl);
        mbedtls_ssl_config_init(&sock->conf);
        mbedtls_x509_crt_init(&sock->cacert);

        ret = mbedtls_x509_crt_parse(&sock->cacert, (const unsigned char *) forgegraal_ca_bundle,
                                     strlen(forgegraal_ca_bundle) + 1);
        if (ret < 0) {
            goto tls_failed;
        }

        ret = mbedtls_ssl_config_defaults(&sock->conf, MBEDTLS_SSL_IS_CLIENT,
                                          MBEDTLS_SSL_TRANSPORT_STREAM, MBEDTLS_SSL_PRESET_DEFAULT);
        if (ret != 0) {
            goto tls_failed;
        }
        /* Verification is required, not optional: the whole reason for a compiled-in CA bundle
           is to verify properly on a machine whose own store cannot. */
        mbedtls_ssl_conf_authmode(&sock->conf, MBEDTLS_SSL_VERIFY_REQUIRED);
        mbedtls_ssl_conf_ca_chain(&sock->conf, &sock->cacert, NULL);
        mbedtls_ssl_conf_rng(&sock->conf, mbedtls_ctr_drbg_random, &fg_drbg);

        ret = mbedtls_ssl_setup(&sock->ssl, &sock->conf);
        if (ret != 0) {
            goto tls_failed;
        }
        /* SNI: without it Discord's front end serves the wrong certificate. */
        ret = mbedtls_ssl_set_hostname(&sock->ssl, host);
        if (ret != 0) {
            goto tls_failed;
        }
        mbedtls_ssl_set_bio(&sock->ssl, &sock->net, mbedtls_net_send, mbedtls_net_recv, NULL);

        while ((ret = mbedtls_ssl_handshake(&sock->ssl)) != 0) {
            if (ret != MBEDTLS_ERR_SSL_WANT_READ && ret != MBEDTLS_ERR_SSL_WANT_WRITE) {
                goto tls_failed;
            }
        }
        sock->is_tls = 1;
    }

    sock->in_use = 1;
    JS_FreeCString(ctx, host);
    return JS_NewInt32(ctx, id);

tls_failed:
    mbedtls_ssl_free(&sock->ssl);
    mbedtls_ssl_config_free(&sock->conf);
    mbedtls_x509_crt_free(&sock->cacert);
    mbedtls_net_free(&sock->net);
    memset(sock, 0, sizeof(*sock));
    {
        JSValue err = fg_throw_mbedtls(ctx, "TLS handshake", ret);
        JS_FreeCString(ctx, host);
        return err;
    }
}

static JSValue fg_read(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv)
{
    int32_t id;
    fg_socket *sock;
    unsigned char buf[16384];
    int ret;

    if (JS_ToInt32(ctx, &id, argv[0])) {
        return JS_EXCEPTION;
    }
    sock = fg_socket_get(ctx, id);
    if (!sock) {
        return JS_EXCEPTION;
    }

    do {
        ret = sock->is_tls ? mbedtls_ssl_read(&sock->ssl, buf, sizeof(buf))
                           : mbedtls_net_recv(&sock->net, buf, sizeof(buf));
    } while (ret == MBEDTLS_ERR_SSL_WANT_READ || ret == MBEDTLS_ERR_SSL_WANT_WRITE);

    /* A clean close and a zero-length read both mean "peer is done", which is what the
       JavaScript side treats as end of stream. */
    if (ret == MBEDTLS_ERR_SSL_PEER_CLOSE_NOTIFY || ret == 0) {
        return JS_NewUint8ArrayCopy(ctx, buf, 0);
    }
    if (ret < 0) {
        return fg_throw_mbedtls(ctx, "read", ret);
    }
    return JS_NewUint8ArrayCopy(ctx, buf, (size_t) ret);
}

static JSValue fg_write(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv)
{
    int32_t id;
    fg_socket *sock;
    size_t len = 0;
    uint8_t *data;
    size_t sent = 0;

    if (JS_ToInt32(ctx, &id, argv[0])) {
        return JS_EXCEPTION;
    }
    sock = fg_socket_get(ctx, id);
    if (!sock) {
        return JS_EXCEPTION;
    }
    data = JS_GetUint8Array(ctx, &len, argv[1]);
    if (!data) {
        return JS_EXCEPTION;
    }

    while (sent < len) {
        int ret = sock->is_tls ? mbedtls_ssl_write(&sock->ssl, data + sent, len - sent)
                               : mbedtls_net_send(&sock->net, data + sent, len - sent);
        if (ret == MBEDTLS_ERR_SSL_WANT_READ || ret == MBEDTLS_ERR_SSL_WANT_WRITE) {
            continue;
        }
        if (ret <= 0) {
            return fg_throw_mbedtls(ctx, "write", ret);
        }
        sent += (size_t) ret;
    }
    return JS_UNDEFINED;
}

static JSValue fg_close(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv)
{
    int32_t id;

    if (JS_ToInt32(ctx, &id, argv[0])) {
        return JS_EXCEPTION;
    }
    /* Closing twice is not an error: a JavaScript stream may well destroy() after the peer
       already went away. */
    if (id >= 0 && id < FG_MAX_SOCKETS && fg_sockets[id].in_use) {
        fg_socket_release(&fg_sockets[id]);
    }
    return JS_UNDEFINED;
}

/* ------------------------------------------------------------------- crypto */

static mbedtls_md_type_t fg_md_type(const char *name)
{
    if (!strcmp(name, "sha256")) return MBEDTLS_MD_SHA256;
    if (!strcmp(name, "sha1")) return MBEDTLS_MD_SHA1;
    if (!strcmp(name, "sha512")) return MBEDTLS_MD_SHA512;
    if (!strcmp(name, "md5")) return MBEDTLS_MD_MD5;
    return MBEDTLS_MD_NONE;
}

static JSValue fg_hash(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv)
{
    const char *name;
    size_t len = 0;
    uint8_t *data;
    unsigned char out[64];
    const mbedtls_md_info_t *info;
    mbedtls_md_type_t type;
    int ret;

    name = JS_ToCString(ctx, argv[0]);
    if (!name) {
        return JS_EXCEPTION;
    }
    type = fg_md_type(name);
    if (type == MBEDTLS_MD_NONE) {
        JSValue err = JS_ThrowInternalError(
            ctx,
            "hash algorithm '%s' is not available in this runtime (sha1, sha256, sha512 and md5 are). "
            "Substituting a different algorithm would silently produce values that do not verify.",
            name);
        JS_FreeCString(ctx, name);
        return err;
    }
    JS_FreeCString(ctx, name);

    data = JS_GetUint8Array(ctx, &len, argv[1]);
    if (!data) {
        return JS_EXCEPTION;
    }
    info = mbedtls_md_info_from_type(type);
    ret = mbedtls_md(info, data, len, out);
    if (ret != 0) {
        return fg_throw_mbedtls(ctx, "hash", ret);
    }
    return JS_NewUint8ArrayCopy(ctx, out, mbedtls_md_get_size(info));
}

static JSValue fg_hmac(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv)
{
    const char *name;
    size_t key_len = 0, data_len = 0;
    uint8_t *key, *data;
    unsigned char out[64];
    const mbedtls_md_info_t *info;
    mbedtls_md_type_t type;
    int ret;

    name = JS_ToCString(ctx, argv[0]);
    if (!name) {
        return JS_EXCEPTION;
    }
    type = fg_md_type(name);
    if (type == MBEDTLS_MD_NONE || type == MBEDTLS_MD_MD5) {
        JSValue err = JS_ThrowInternalError(
            ctx, "HMAC algorithm '%s' is not available in this runtime (sha1, sha256 and sha512 are).",
            name);
        JS_FreeCString(ctx, name);
        return err;
    }
    JS_FreeCString(ctx, name);

    key = JS_GetUint8Array(ctx, &key_len, argv[1]);
    data = JS_GetUint8Array(ctx, &data_len, argv[2]);
    if (!key || !data) {
        return JS_EXCEPTION;
    }
    info = mbedtls_md_info_from_type(type);
    ret = mbedtls_md_hmac(info, key, key_len, data, data_len, out);
    if (ret != 0) {
        return fg_throw_mbedtls(ctx, "hmac", ret);
    }
    return JS_NewUint8ArrayCopy(ctx, out, mbedtls_md_get_size(info));
}

static JSValue fg_random_bytes(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv)
{
    int32_t len;
    unsigned char *buf;
    int ret;
    JSValue out;

    if (JS_ToInt32(ctx, &len, argv[0]) || len < 0) {
        return JS_ThrowTypeError(ctx, "randomBytes(length) needs a non-negative length");
    }
    if (fg_rng_init() != 0) {
        return JS_ThrowInternalError(ctx, "could not seed the random number generator");
    }
    buf = js_malloc(ctx, len ? (size_t) len : 1);
    if (!buf) {
        return JS_EXCEPTION;
    }
    ret = mbedtls_ctr_drbg_random(&fg_drbg, buf, (size_t) len);
    if (ret != 0) {
        js_free(ctx, buf);
        return fg_throw_mbedtls(ctx, "randomBytes", ret);
    }
    out = JS_NewUint8ArrayCopy(ctx, buf, (size_t) len);
    js_free(ctx, buf);
    return out;
}

/* -------------------------------------------------------------- compression */

static JSValue fg_zlib(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv,
                       int compress, int raw)
{
    size_t len = 0;
    uint8_t *data = JS_GetUint8Array(ctx, &len, argv[0]);
    mz_ulong out_len;
    unsigned char *out;
    JSValue result;
    int ret;

    if (!data) {
        return JS_EXCEPTION;
    }

    if (compress) {
        out_len = mz_compressBound((mz_ulong) len);
        out = js_malloc(ctx, out_len ? out_len : 1);
        if (!out) {
            return JS_EXCEPTION;
        }
        ret = mz_compress2(out, &out_len, data, (mz_ulong) len, MZ_DEFAULT_COMPRESSION);
        if (ret != MZ_OK) {
            js_free(ctx, out);
            return JS_ThrowInternalError(ctx, "deflate failed (%d)", ret);
        }
    } else {
        /* Inflating needs a guess at the output size; grow until it fits rather than
           capping, so a large gateway frame is not silently truncated. */
        size_t capacity = len * 4 + 1024;
        for (;;) {
            out = js_malloc(ctx, capacity);
            if (!out) {
                return JS_EXCEPTION;
            }
            out_len = (mz_ulong) capacity;
            ret = mz_uncompress(out, &out_len, data, (mz_ulong) len);
            if (ret == MZ_OK) {
                break;
            }
            js_free(ctx, out);
            if (ret != MZ_BUF_ERROR || capacity > (64u << 20)) {
                return JS_ThrowInternalError(ctx, "inflate failed (%d)", ret);
            }
            capacity *= 4;
        }
    }

    result = JS_NewUint8ArrayCopy(ctx, out, (size_t) out_len);
    js_free(ctx, out);
    (void) raw;
    return result;
}

static JSValue fg_inflate(JSContext *ctx, JSValueConst t, int argc, JSValueConst *argv)
{
    return fg_zlib(ctx, t, argc, argv, 0, argc > 1 ? JS_ToBool(ctx, argv[1]) : 0);
}

static JSValue fg_deflate(JSContext *ctx, JSValueConst t, int argc, JSValueConst *argv)
{
    return fg_zlib(ctx, t, argc, argv, 1, argc > 1 ? JS_ToBool(ctx, argv[1]) : 0);
}

/* ---------------------------------------------------------------------- text */

static JSValue fg_encode_utf8(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv)
{
    size_t len;
    const char *str = JS_ToCStringLen(ctx, &len, argv[0]);
    JSValue out;

    if (!str) {
        return JS_EXCEPTION;
    }
    out = JS_NewUint8ArrayCopy(ctx, (const uint8_t *) str, len);
    JS_FreeCString(ctx, str);
    return out;
}

static JSValue fg_decode_utf8(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv)
{
    size_t len = 0;
    uint8_t *data = JS_GetUint8Array(ctx, &len, argv[0]);

    if (!data) {
        return JS_EXCEPTION;
    }
    return JS_NewStringLen(ctx, (const char *) data, len);
}

/* ------------------------------------------------------------------ install */

/* evalScript(source, filename): the engine's std.evalScript names every script "<evalScript>", which
   makes every stack frame anonymous. Loaded modules need their own file name, both for readable errors
   and for the packages (bindings, depd, ...) that read it back out of a stack trace. */
static JSValue fg_eval_script(JSContext *ctx, JSValueConst this_val, int argc, JSValueConst *argv)
{
    size_t len;
    const char *source, *filename;
    JSValue result;

    if (argc < 2) return JS_ThrowTypeError(ctx, "evalScript(source, filename) expects two arguments");
    source = JS_ToCStringLen(ctx, &len, argv[0]);
    if (!source) return JS_EXCEPTION;
    filename = JS_ToCString(ctx, argv[1]);
    if (!filename) {
        JS_FreeCString(ctx, source);
        return JS_EXCEPTION;
    }
    result = JS_Eval(ctx, source, len, filename, JS_EVAL_TYPE_GLOBAL);
    JS_FreeCString(ctx, source);
    JS_FreeCString(ctx, filename);
    return result;
}

static const JSCFunctionListEntry fg_native_funcs[] = {
    JS_CFUNC_DEF("evalScript", 2, fg_eval_script),
    JS_CFUNC_DEF("connect", 3, fg_connect),
    JS_CFUNC_DEF("read", 1, fg_read),
    JS_CFUNC_DEF("write", 2, fg_write),
    JS_CFUNC_DEF("close", 1, fg_close),
    JS_CFUNC_DEF("hash", 2, fg_hash),
    JS_CFUNC_DEF("hmac", 3, fg_hmac),
    JS_CFUNC_DEF("randomBytes", 1, fg_random_bytes),
    JS_CFUNC_DEF("inflate", 2, fg_inflate),
    JS_CFUNC_DEF("deflate", 2, fg_deflate),
    JS_CFUNC_DEF("encodeUtf8", 1, fg_encode_utf8),
    JS_CFUNC_DEF("decodeUtf8", 1, fg_decode_utf8),
};

void forgegraal_napi_init(JSContext *ctx);
extern const JSCFunctionListEntry forgegraal_napi_funcs[];
extern const size_t forgegraal_napi_funcs_count;

void forgegraal_native_init(JSContext *ctx)
{
    JSValue global, native;

#ifdef _WIN32
    /* Winsock needs starting before any socket call, and nothing else will do it for us. */
    WSADATA wsa;
    WSAStartup(MAKEWORD(2, 2), &wsa);
#endif

    global = JS_GetGlobalObject(ctx);
    native = JS_NewObject(ctx);
    JS_SetPropertyFunctionList(ctx, native, fg_native_funcs,
                               sizeof(fg_native_funcs) / sizeof(fg_native_funcs[0]));
    /* Node-API: dlopen/LoadLibrary of `.node` addons plus the pump that delivers their async results. */
    forgegraal_napi_init(ctx);
    JS_SetPropertyFunctionList(ctx, native, forgegraal_napi_funcs, (int) forgegraal_napi_funcs_count);
    JS_SetPropertyStr(ctx, native, "backend", JS_NewString(ctx, "c"));
#ifdef _WIN32
    JS_SetPropertyStr(ctx, native, "platform", JS_NewString(ctx, "win32"));
#else
    JS_SetPropertyStr(ctx, native, "platform", JS_NewString(ctx, "linux"));
#endif
    /* The architecture this binary was built for, which is what a native addon has to match. */
#if defined(__x86_64__) || defined(_M_X64)
    JS_SetPropertyStr(ctx, native, "arch", JS_NewString(ctx, "x64"));
#elif defined(__aarch64__) || defined(_M_ARM64)
    JS_SetPropertyStr(ctx, native, "arch", JS_NewString(ctx, "arm64"));
#elif defined(__arm__)
    JS_SetPropertyStr(ctx, native, "arch", JS_NewString(ctx, "arm"));
#else
    JS_SetPropertyStr(ctx, native, "arch", JS_NewString(ctx, "ia32"));
#endif
#ifdef __GLIBC__
    /* Native addons pick their glibc or musl prebuilt by asking this (Node exposes it through
       process.report), so it has to be truthful rather than guessed from the filesystem. */
    JS_SetPropertyStr(ctx, native, "glibc", JS_NewString(ctx, gnu_get_libc_version()));
#endif
    JS_SetPropertyStr(ctx, global, "__forgegraal_native", native);
    JS_FreeValue(ctx, global);
}
