#!/bin/sh
# Compiles a PEM certificate bundle into a C string.
#
# The bundle is baked into the binary on purpose. A machine old enough to need this runtime has a
# certificate store years out of date, which would reject Discord outright; verifying against roots
# shipped with the build is what makes TLS work there. It is the same reasoning Node uses in
# shipping its own Mozilla CA snapshot rather than trusting the OS.
set -eu

SOURCE="${1:-/etc/ssl/certs/ca-certificates.crt}"
OUTPUT="${2:-$(dirname "$0")/ca_bundle.c}"

[ -r "$SOURCE" ] || { echo "error: cannot read $SOURCE" >&2; exit 1; }

{
	echo "/* Generated by gen-ca-bundle.sh from $SOURCE. Do not edit by hand. */"
	echo "const char forgegraal_ca_bundle[] ="
	# Each PEM line becomes a C string literal. Quotes and backslashes cannot appear in PEM, but
	# CR can if the source has Windows line endings, so it is stripped.
	sed -e 's/\r$//' -e 's/"/\\"/g' -e 's/^/"/' -e 's/$/\\n"/' "$SOURCE"
	echo ";"
} > "$OUTPUT"

COUNT=$(grep -c "BEGIN CERTIFICATE" "$SOURCE" || true)
echo "wrote $OUTPUT ($COUNT root certificates)"
