/*
 * SPDX-License-Identifier: LGPL-3.0-or-later
 * ForgeGraal Autonomous Evolution Engine
 */

import { ArgType, NativeFunction } from "@tryforge/forgescript";

export default new NativeFunction({
	name: "$dummyFeature",
	version: "1.0.0",
	description: "Dummy generated by fallback",
	unwrap: true,
	output: ArgType.String,
	execute(_ctx) {
		return this.success("dummy");
	},
});
