/*
 * SPDX-License-Identifier: LGPL-3.0-or-later
 * ForgeGraal Native Functions Registry (Generated by Python Agent Engine)
 */

import binaryArchitecture from "./binaryArchitecture.js";
import binaryFormat from "./binaryFormat.js";
import compileBinary from "./compileBinary.js";
import graalVersion from "./graalVersion.js";
import is32BitOrLegacy from "./is32BitOrLegacy.js";
import isIsh from "./isIsh.js";
import isLegacyWindows from "./isLegacyWindows.js";
import isTargetSupported from "./isTargetSupported.js";
import packageManager from "./packageManager.js";
import supportedTargets from "./supportedTargets.js";
import targetBits from "./targetBits.js";

export const nativeFunctions = [
	binaryArchitecture,
	binaryFormat,
	compileBinary,
	graalVersion,
	is32BitOrLegacy,
	isIsh,
	isLegacyWindows,
	isTargetSupported,
	packageManager,
	supportedTargets,
	targetBits,
];

export {
	binaryArchitecture,
	binaryFormat,
	compileBinary,
	graalVersion,
	is32BitOrLegacy as is32BitOrLegacyFn,
	isIsh,
	isLegacyWindows,
	isTargetSupported,
	packageManager,
	supportedTargets,
	targetBits,
};
