/*
 * SPDX-License-Identifier: LGPL-3.0-or-later
 * ForgeGraal Native Functions Registry (Generated by Python Agent Engine)
 */

import binaryArchitecture from "./binaryArchitecture.js";
import binaryExtension from "./binaryExtension.js";
import binaryFormat from "./binaryFormat.js";
import binarySize from "./binarySize.js";
import canPackageOnBun from "./canPackageOnBun.js";
import compileBinary from "./compileBinary.js";
import dbDriverCompat from "./dbDriverCompat.js";
import dummyFeature from "./dummyFeature.js";
import dummyFeatureFallback from "./dummyFeatureFallback.js";
import generateSeaConfig from "./generateSeaConfig.js";
import graalVersion from "./graalVersion.js";
import is32BitOrLegacy from "./is32BitOrLegacy.js";
import is32BitTarget from "./is32BitTarget.js";
import is64BitTarget from "./is64BitTarget.js";
import isArmTarget from "./isArmTarget.js";
import isIsh from "./isIsh.js";
import isLegacyWindows from "./isLegacyWindows.js";
import isTargetSupported from "./isTargetSupported.js";
import listPlatforms from "./listPlatforms.js";
import packageManager from "./packageManager.js";
import packagerType from "./packagerType.js";
import sha256Binary from "./sha256Binary.js";
import supportedTargets from "./supportedTargets.js";
import targetBits from "./targetBits.js";
import targetDescription from "./targetDescription.js";
import targetPlatform from "./targetPlatform.js";
import verifyBinaryHeader from "./verifyBinaryHeader.js";

export const nativeFunctions = [
	binaryArchitecture,
	binaryExtension,
	binaryFormat,
	binarySize,
	canPackageOnBun,
	compileBinary,
	dbDriverCompat,
	dummyFeature,
	dummyFeatureFallback,
	generateSeaConfig,
	graalVersion,
	is32BitOrLegacy,
	is32BitTarget,
	is64BitTarget,
	isArmTarget,
	isIsh,
	isLegacyWindows,
	isTargetSupported,
	listPlatforms,
	packageManager,
	packagerType,
	sha256Binary,
	supportedTargets,
	targetBits,
	targetDescription,
	targetPlatform,
	verifyBinaryHeader,
];

export {
	binaryArchitecture,
	binaryExtension,
	binaryFormat,
	binarySize,
	canPackageOnBun,
	compileBinary,
	dbDriverCompat,
	dummyFeature,
	dummyFeatureFallback,
	generateSeaConfig,
	graalVersion,
	is32BitOrLegacy as is32BitOrLegacyFn,
	is32BitTarget,
	is64BitTarget,
	isArmTarget,
	isIsh,
	isLegacyWindows,
	isTargetSupported,
	listPlatforms,
	packageManager,
	packagerType,
	sha256Binary,
	supportedTargets,
	targetBits,
	targetDescription,
	targetPlatform,
	verifyBinaryHeader,
};
