import { cpSync, existsSync, mkdirSync, mkdtempSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { basename, dirname, join, resolve } from "node:path";
import { RuntimeError } from "../structures";

/**
 * Turns a folder of static files (a `vite build`, Create React App or `next export` output, a plain
 * HTML site) into something ForgeGraal can package like any other program: a generated web server plus
 * the files it serves.
 *
 * The server is plain JavaScript over `http`, `fs`, `path` and `zlib`, so the same source runs on the
 * native host and on Node.js. It serves the site the way a static host would: correct MIME types,
 * ETag and Last-Modified with 304 replies, byte ranges (video seeking), gzip for text, an index file for
 * directories, optional single-page-app fallback to `index.html`, and no way out of the site folder.
 */
export interface StaticSiteOptions {
	/** Answer unknown routes that look like pages with `index.html`, so client-side routing works. */
	spa?: boolean;
	/** TCP port. `PORT` in the environment and `--port` on the command line override it. Default 8080. */
	port?: number;
	/** Interface to listen on. Default all IPv4 interfaces. */
	host?: string;
	/** File served for a directory. Default `index.html`. */
	index?: string;
}

export interface MaterializedSite {
	/** A temporary project directory holding `package.json`, `server.js` and `site/`. */
	root: string;
	/** The generated server, to be compiled like any entrypoint. */
	entrypoint: string;
	/** Files served, for reporting. */
	cleanup: () => void;
}

const SKIPPED = new Set(["node_modules", ".git", ".DS_Store", "Thumbs.db"]);

export class StaticSite {
	/** A directory, or an `.html` file, is a site rather than a program. */
	public static isSiteEntry(entrypoint: string): boolean {
		const path = resolve(entrypoint);
		if (!existsSync(path)) return false;
		const info = statSync(path);
		if (info.isDirectory()) return true;
		return /\.html?$/i.test(path);
	}

	public static siteDirectory(entrypoint: string): string {
		const path = resolve(entrypoint);
		return statSync(path).isDirectory() ? path : dirname(path);
	}

	public static materialize(entrypoint: string, options: StaticSiteOptions = {}): MaterializedSite {
		const siteDir = StaticSite.siteDirectory(entrypoint);
		const index = options.index ?? "index.html";
		if (!existsSync(join(siteDir, index))) {
			throw new RuntimeError(
				`'${siteDir}' has no ${index}. Point forgegraal at the folder your build tool produced (dist, build, out), ` +
					"or pass --index <file> if the entry page has another name."
			);
		}
		const port = options.port ?? 8080;
		if (!Number.isInteger(port) || port < 0 || port > 65535) {
			throw new RuntimeError(`Invalid port ${options.port}: expected a whole number from 0 to 65535`);
		}

		const root = mkdtempSync(join(tmpdir(), "forgegraal-site-"));
		try {
			const name = basename(siteDir).replace(/[^A-Za-z0-9._-]/g, "-") || "site";
			writeFileSync(
				join(root, "package.json"),
				JSON.stringify({ name, version: "1.0.0", private: true, main: "server.js" })
			);
			cpSync(siteDir, join(root, "site"), {
				recursive: true,
				dereference: true,
				filter: (source) => !SKIPPED.has(basename(source)),
			});
			writeFileSync(
				join(root, "server.js"),
				renderServer({ spa: Boolean(options.spa), port, host: options.host ?? "0.0.0.0", index })
			);
			mkdirSync(join(root, "site"), { recursive: true });
		} catch (error) {
			rmSync(root, { recursive: true, force: true });
			throw error;
		}
		return {
			root,
			entrypoint: join(root, "server.js"),
			cleanup: () => rmSync(root, { recursive: true, force: true }),
		};
	}
}

interface ServerConfig {
	spa: boolean;
	port: number;
	host: string;
	index: string;
}

function renderServer(config: ServerConfig): string {
	return `"use strict";
// Generated by ForgeGraal: serves ./site.
var http = require("http");
var fs = require("fs");
var path = require("path");
var zlib = require("zlib");

var CONFIG = ${JSON.stringify(config)};

function argument(name) {
	var args = process.argv.slice(2);
	for (var i = 0; i < args.length; i++) {
		if (args[i] === name && i + 1 < args.length) return args[i + 1];
		if (args[i].indexOf(name + "=") === 0) return args[i].slice(name.length + 1);
	}
	return undefined;
}

var port = Number(argument("--port") || process.env.PORT || CONFIG.port);
var host = argument("--host") || process.env.HOST || CONFIG.host;
var spa = process.argv.indexOf("--spa") !== -1 ? true : CONFIG.spa;
var root = path.join(__dirname, "site");

var TYPES = {
	".html": "text/html; charset=utf-8", ".htm": "text/html; charset=utf-8", ".css": "text/css; charset=utf-8",
	".js": "text/javascript; charset=utf-8", ".mjs": "text/javascript; charset=utf-8", ".cjs": "text/javascript; charset=utf-8",
	".json": "application/json; charset=utf-8", ".map": "application/json; charset=utf-8", ".webmanifest": "application/manifest+json",
	".txt": "text/plain; charset=utf-8", ".xml": "application/xml; charset=utf-8", ".csv": "text/csv; charset=utf-8",
	".md": "text/markdown; charset=utf-8", ".svg": "image/svg+xml", ".png": "image/png", ".jpg": "image/jpeg",
	".jpeg": "image/jpeg", ".gif": "image/gif", ".webp": "image/webp", ".avif": "image/avif", ".ico": "image/x-icon",
	".bmp": "image/bmp", ".woff": "font/woff", ".woff2": "font/woff2", ".ttf": "font/ttf", ".otf": "font/otf",
	".eot": "application/vnd.ms-fontobject", ".mp3": "audio/mpeg", ".wav": "audio/wav", ".ogg": "audio/ogg",
	".mp4": "video/mp4", ".webm": "video/webm", ".pdf": "application/pdf", ".zip": "application/zip",
	".wasm": "application/wasm", ".gz": "application/gzip"
};
var COMPRESSIBLE = /^(text\\/|application\\/(json|javascript|xml|manifest\\+json|wasm)|image\\/svg\\+xml|font\\/(ttf|otf)|application\\/vnd\\.ms-fontobject)/;
var HASHED = /[.-][A-Za-z0-9_-]{8,}\\.[A-Za-z0-9]+$/;

var crcTable = null;
function crc32(bytes) {
	if (!crcTable) {
		crcTable = new Array(256);
		for (var n = 0; n < 256; n++) {
			var c = n;
			for (var k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
			crcTable[n] = c >>> 0;
		}
	}
	var crc = 0xffffffff;
	for (var i = 0; i < bytes.length; i++) crc = crcTable[(crc ^ bytes[i]) & 0xff] ^ (crc >>> 8);
	return (crc ^ 0xffffffff) >>> 0;
}

/* gzip = 10-byte header + raw deflate + CRC32 and length; built from the raw deflate the host provides. */
function gzip(bytes) {
	var body = zlib.deflateRawSync(bytes);
	var out = Buffer.alloc(body.length + 18);
	out[0] = 0x1f; out[1] = 0x8b; out[2] = 8; out[9] = 3;
	body.copy(out, 10);
	out.writeUInt32LE(crc32(bytes), 10 + body.length);
	out.writeUInt32LE(bytes.length >>> 0, 14 + body.length);
	return out;
}

var gzipCache = {};

function send(res, status, headers, body, head) {
	headers["Content-Length"] = body.length;
	res.writeHead(status, headers);
	res.end(head ? undefined : body);
}

function fail(res, status, message, head) {
	var page = null;
	if (status === 404) {
		var custom = path.join(root, "404.html");
		try { if (fs.statSync(custom).isFile()) page = fs.readFileSync(custom); } catch (e) { /* no custom page */ }
	}
	if (page) return send(res, status, { "Content-Type": "text/html; charset=utf-8" }, page, head);
	send(res, status, { "Content-Type": "text/plain; charset=utf-8" }, Buffer.from(message), head);
}

function statOf(file) {
	try { return fs.statSync(file); } catch (e) { return null; }
}

function handle(req, res) {
	var head = req.method === "HEAD";
	if (req.method !== "GET" && !head) {
		res.setHeader("Allow", "GET, HEAD");
		return fail(res, 405, "Method Not Allowed");
	}
	var target;
	try { target = new URL(req.url, "http://localhost"); } catch (e) { return fail(res, 400, "Bad Request", head); }
	var pathname;
	try { pathname = decodeURIComponent(target.pathname); } catch (e) { return fail(res, 400, "Bad Request", head); }
	if (pathname.indexOf("\\0") !== -1) return fail(res, 400, "Bad Request", head);

	var file = path.join(root, pathname);
	if (file !== root && file.indexOf(root + path.sep) !== 0) return fail(res, 403, "Forbidden", head);

	var info = statOf(file);
	if (info && info.isDirectory()) {
		if (pathname.charAt(pathname.length - 1) !== "/") {
			res.writeHead(301, { Location: pathname + "/" + target.search, "Content-Length": 0 });
			return res.end();
		}
		file = path.join(file, CONFIG.index);
		info = statOf(file);
	}
	if (!info || !info.isFile()) {
		var looksLikePage = path.extname(pathname) === "";
		var accept = String(req.headers.accept || "");
		if (spa && looksLikePage && (accept === "" || accept.indexOf("text/html") !== -1 || accept.indexOf("*/*") !== -1)) {
			file = path.join(root, CONFIG.index);
			info = statOf(file);
		}
		if (!info || !info.isFile()) return fail(res, 404, "Not Found", head);
	}

	var type = TYPES[path.extname(file).toLowerCase()] || "application/octet-stream";
	var etag = 'W/"' + info.size.toString(16) + "-" + Math.floor(info.mtimeMs).toString(16) + '"';
	var headers = {
		"Content-Type": type,
		"Accept-Ranges": "bytes",
		"ETag": etag,
		"Last-Modified": new Date(info.mtimeMs).toUTCString(),
		"Cache-Control": HASHED.test(path.basename(file)) ? "public, max-age=31536000, immutable" : "public, max-age=0, must-revalidate",
		"X-Content-Type-Options": "nosniff"
	};
	var noneMatch = req.headers["if-none-match"];
	if (noneMatch && noneMatch.split(/\\s*,\\s*/).indexOf(etag) !== -1) {
		res.writeHead(304, headers);
		return res.end();
	}

	var body = fs.readFileSync(file);
	var range = req.headers.range;
	if (range && /^bytes=/.test(range)) {
		var m = /^bytes=(\\d*)-(\\d*)$/.exec(range);
		var start = m && m[1] !== "" ? Number(m[1]) : NaN;
		var end = m && m[2] !== "" ? Number(m[2]) : NaN;
		if (!m || (isNaN(start) && isNaN(end))) {
			headers["Content-Range"] = "bytes */" + body.length;
			return send(res, 416, headers, Buffer.alloc(0), head);
		}
		if (isNaN(start)) { start = Math.max(0, body.length - end); end = body.length - 1; }
		else if (isNaN(end) || end >= body.length) end = body.length - 1;
		if (start > end || start >= body.length) {
			headers["Content-Range"] = "bytes */" + body.length;
			return send(res, 416, headers, Buffer.alloc(0), head);
		}
		headers["Content-Range"] = "bytes " + start + "-" + end + "/" + body.length;
		return send(res, 206, headers, body.slice(start, end + 1), head);
	}

	if (body.length > 1024 && COMPRESSIBLE.test(type) && /\\bgzip\\b/.test(String(req.headers["accept-encoding"] || ""))) {
		var key = file + ":" + etag;
		var packed = gzipCache[key] || (gzipCache[key] = gzip(body));
		headers["Content-Encoding"] = "gzip";
		headers["Vary"] = "Accept-Encoding";
		body = packed;
	}
	send(res, 200, headers, body, head);
}

var server = http.createServer(function (req, res) {
	try {
		handle(req, res);
	} catch (error) {
		console.error(error && error.stack || error);
		if (!res.headersSent) fail(res, 500, "Internal Server Error");
		else res.end();
	}
});

server.on("error", function (error) {
	if (error && error.code === "EADDRINUSE") console.error("Port " + port + " is already in use. Pass --port <number> or set PORT.");
	else console.error(error && error.message || error);
	process.exit(1);
});

server.listen(port, host, function () {
	var address = server.address();
	var shown = host === "0.0.0.0" || host === "::" ? "localhost" : host;
	console.log("Serving " + root + " on http://" + shown + ":" + address.port + (spa ? " (single-page-app fallback on)" : ""));
});
`;
}
