#ifndef GRAAK_V8_VERSION_H_
#define GRAAK_V8_VERSION_H_
#define V8_MAJOR_VERSION 7
#define V8_MINOR_VERSION 7
#define V8_BUILD_NUMBER 299
#define V8_PATCH_LEVEL 11
#define V8_IS_CANDIDATE_VERSION 0
#define V8_VERSION_STRING "7.7.299.11-graak"
#endif
