#!/usr/bin/env python3
"""Generates the Unicode break-property tables Intl.Segmenter needs.

Run against a Unicode Character Database directory:

    gen-segmenter-tables.py <ucd-dir> [output]

The output is a JavaScript module holding one packed range table per property set. Packing
matters: the raw data is thousands of ranges, and an implementation that shipped them as an array
of objects would cost far more than the runtime it is meant to fit on. Each table is a flat array
of [start, length, value] triples, delta-encoded and base-36 text, which the runtime expands once
at load.

The tables are data from the Unicode Character Database (unicode.org), used under the Unicode
licence. Regenerate them rather than editing by hand.
"""
import pathlib
import re
import sys

LINE = re.compile(r"^([0-9A-F]{4,6})(?:\.\.([0-9A-F]{4,6}))?\s*;\s*([A-Za-z_]+)")
# InCB entries carry a second field: "0915 ; InCB; Consonant".
INCB = re.compile(r"^([0-9A-F]{4,6})(?:\.\.([0-9A-F]{4,6}))?\s*;\s*InCB;\s*([A-Za-z_]+)")


def parse_incb(path):
    """Reads Indic_Conjunct_Break values, needed for grapheme rule GB9c (Unicode 15.1)."""
    out = []
    for line in pathlib.Path(path).read_text(encoding="utf-8").splitlines():
        line = line.split("#")[0].strip()
        match = INCB.match(line) if line else None
        if match:
            start = int(match.group(1), 16)
            end = int(match.group(2), 16) if match.group(2) else start
            out.append((start, end, "InCB_" + match.group(3)))
    return out


def parse(path):
    """Reads a UCD property file into (start, end, value) tuples."""
    out = []
    for line in pathlib.Path(path).read_text(encoding="utf-8").splitlines():
        line = line.split("#")[0].strip()
        if not line:
            continue
        match = LINE.match(line)
        if not match:
            continue
        start = int(match.group(1), 16)
        end = int(match.group(2), 16) if match.group(2) else start
        out.append((start, end, match.group(3)))
    return out


def pack(ranges, values):
    """Delta-encodes ranges into a compact base-36 string.

    Format per entry: <delta from previous end>,<length-1>,<value index>, all base 36, separated
    by '.'. Sorted so the deltas stay small, which is what makes the text short.
    """
    index = {name: i for i, name in enumerate(values)}
    parts = []
    previous = 0
    for start, end, value in sorted(ranges):
        if value not in index:
            continue
        parts.append(
            f"{start - previous:x}.{end - start:x}.{index[value]:x}"
        )
        previous = end
    return ",".join(parts)


def main():
    ucd = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else ".")
    output = pathlib.Path(sys.argv[2] if len(sys.argv) > 2 else "segmenter-tables.js")

    grapheme = parse(ucd / "GraphemeBreakProperty.txt")
    word = parse(ucd / "WordBreakProperty.txt")
    # Extended_Pictographic lives in emoji-data.txt and is needed for GB11 (emoji ZWJ sequences).
    emoji = [r for r in parse(ucd / "emoji-data.txt") if r[2] == "Extended_Pictographic"]
    incb = parse_incb(ucd / "DerivedCoreProperties.txt")

    # One table per property. Merging them would break lookup: a code point can carry a
    # Grapheme_Cluster_Break value AND be Extended_Pictographic AND have an InCB value, and a
    # single sorted table can only answer with one of them.
    grapheme_values = sorted({v for _, _, v in grapheme})
    word_values = sorted({v for _, _, v in word})
    picto_values = ["Extended_Pictographic"]
    incb_values = sorted({v for _, _, v in incb})

    tables = {
        "GRAPHEME": (grapheme, grapheme_values),
        "WORD": (word, word_values),
        "PICTO": (emoji, picto_values),
        "INCB": (incb, incb_values),
    }

    lines = [
        "/*",
        " * Unicode break-property tables, generated by gen-segmenter-tables.py from the Unicode",
        " * Character Database. Do not edit by hand -- regenerate instead.",
        " *",
        " * Data from unicode.org, used under the Unicode licence. Packed as delta-encoded base-16",
        " * ranges because the raw property files run to thousands of entries and this has to fit on",
        " * machines with very little to spare. One table per property: a code point can hold several",
        " * of these at once, so a single merged table could only answer with one of them.",
        " */",
        "",
    ]
    for name, (ranges, values) in tables.items():
        rendered = ", ".join(f'"{v}"' for v in values)
        lines.append(f"export const {name}_VALUES = [{rendered}];")
    lines.append("")
    for name, (ranges, values) in tables.items():
        lines.append(f"export const {name}_TABLE =")
        lines.append(f'\t"{pack(ranges, values)}";')
        lines.append("")

    body = "\n".join(lines)
    output.write_text(body, encoding="utf-8")
    print(
        f"wrote {output} (grapheme {len(grapheme)}, word {len(word)}, "
        f"pictographic {len(emoji)}, InCB {len(incb)} ranges, {len(body) // 1024} KB)"
    )


if __name__ == "__main__":
    main()
